services:
  worker-service:
    build:
      context: .
    #      target: final
    env_file:
      - .env
      - ../.env
    expose:
      - "${WORKER_SERVICE_INTERNAL_PORT}"
    volumes:
      - .:/worker-service
    deploy:
      mode: replicated
      replicas: ${WORKER_SERVICE_COUNT}