server:
  port: ${WORKER_SERVICE_INTERNAL_PORT}

spring:
  jackson:
    property-naming-strategy: UPPER_CAMEL_CASE
    mapper:
      accept-case-insensitive-properties: true
  rabbitmq:
    password: "${RABBITMQ_DEFAULT_PASSWORD}"
    username: "${RABBITMQ_DEFAULT_USER}"

app:
  rabbitmq:
    worker:
      queue: "${RABBITMQ_WORKER_QUEUE}"
      exchange: "${RABBITMQ_WORKER_EXCHANGE}"
      routing-key: "${RABBITMQ_WORKER_ROUTING_KEY}"
      concurrency: "${CONCURRENCY_PER_WORKER}"
    manager:
      queue: "${RABBITMQ_MANAGER_QUEUE}"
      exchange: "${RABBITMQ_MANAGER_EXCHANGE}"
      routing-key: "${RABBITMQ_MANAGER_ROUTING_KEY}"
  manager:
    port: "${MANAGER_SERVICE_INTERNAL_PORT}"