services:
  manager-service:
    build:
      context: .
    #      target: final
    env_file:
      - .env
      - ../.env
    ports:
      - "${MANAGER_SERVICE_EXTERNAL_PORT}:${MANAGER_SERVICE_INTERNAL_PORT}"
    volumes:
      - .:/manager-service
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data: