services:
  manager-service:
    build:
      context: .
    #      target: final
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: "${RABBITMQ_DEFAULT_USER}"
      SPRING_RABBITMQ_PASSWORD: "${RABBITMQ_DEFAULT_PASSWORD}"
      RABBITMQ_WORKER_QUEUE: "${RABBITMQ_WORKER_QUEUE}"
      RABBITMQ_WORKER_EXCHANGE: "${RABBITMQ_WORKER_EXCHANGE}"
      RABBITMQ_WORKER_ROUTING_KEY: "${RABBITMQ_WORKER_ROUTING_KEY}"
      RABBITMQ_MANAGER_QUEUE: "${RABBITMQ_MANAGER_QUEUE}"
      RABBITMQ_MANAGER_EXCHANGE: "${RABBITMQ_MANAGER_EXCHANGE}"
      RABBITMQ_MANAGER_ROUTING_KEY: "${RABBITMQ_MANAGER_ROUTING_KEY}"
    env_file:
      - .env
      - ../.env
    ports:
      - "${MANAGER_SERVICE_EXTERNAL_PORT}:${MANAGER_SERVICE_INTERNAL_PORT}"
    volumes:
      - .:/manager-service
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 7s
      timeout: 4s
      retries: 3

volumes:
  mongo_data:
  rabbitmq_data: