#!/bin/bash
rm dupl_time_table.csv scat_time_table.csv
touch dupl_time_table.csv scat_time_table.csv
make -s duplicated && make -s scattered
for i in $(seq 1 12)
do
	/usr/bin/mpiexec -np "$i" ~/nsu/opp/lab1/scattered 
       	/usr/bin/mpiexec -np "$i" ~/nsu/opp/lab1/duplicated
done
