server:
  port: ${MANAGER_SERVICE_EXTERNAL_PORT}

spring:
  mongodb:
    uri: mongodb://mongodb1:27017,mongodb2:27017,mongodb3:27017/${MONGO_INITDB_DATABASE}?replicaSet=rs0
  data:
    mongodb:
      auto-index-creation: true
  rabbitmq:
    password: "${SPRING_RABBITMQ_PASSWORD}"
    username: "${SPRING_RABBITMQ_USERNAME}"
    host: "${SPRING_RABBITMQ_HOST}"
    port: "${SPRING_RABBITMQ_PORT}"

task:
  timeout:
    duration:
      minutes: "${TASK_TIMEOUT_DURATION_MINUTES}"

mongodb:
  collection:
    name: "${MONGO_INITDB_DATABASE}"

app:
  rabbitmq:
    worker:
      queue: "${RABBITMQ_WORKER_QUEUE}"
      exchange: "${RABBITMQ_WORKER_EXCHANGE}"
      routing-key: "${RABBITMQ_WORKER_ROUTING_KEY}"
    manager:
      queue: "${RABBITMQ_MANAGER_QUEUE}"
      exchange: "${RABBITMQ_MANAGER_EXCHANGE}"
      routing-key: "${RABBITMQ_MANAGER_ROUTING_KEY}"
  worker:
    count: "${WORKER_SERVICE_COUNT}"
    port: "${WORKER_SERVICE_INTERNAL_PORT}"
  alphabet:
    - "0"
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "a"
    - "b"
    - "c"
    - "d"
    - "e"
    - "f"
    - "g"
    - "h"
    - "i"
    - "j"
    - "k"
    - "l"
    - "m"
    - "n"
    - "o"
    - "p"
    - "q"
    - "r"
    - "s"
    - "t"
    - "u"
    - "v"
    - "w"
    - "x"
    - "y"
    - "z"