server:
  port: ${MANAGER_SERVICE_EXTERNAL_PORT}

spring:
  mongodb:
    uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
  data:
    mongodb:
      auto-index-creation: true

task:
  timeout:
    duration:
      minutes: "${TASK_TIMEOUT_DURATION_MINUTES}"

mongodb:
  collection:
    name: "${MONGO_INITDB_DATABASE}"

app:
  worker:
    count: "${WORKER_SERVICE_COUNT}"