server:
  port: ${MANAGER_SERVICE_EXTERNAL_PORT}

spring:
  mongodb:
    uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin&retryWrites=false
  data:
    mongodb:
      auto-index-creation: true

task:
  timeout:
    duration:
      minutes: "${TASK_TIMEOUT_DURATION_MINUTES}"

mongodb:
  collection:
    name: "${MONGO_INITDB_DATABASE}"

app:
  worker:
    count: "${WORKER_SERVICE_COUNT}"
    port: "${WORKER_SERVICE_INTERNAL_PORT}"
  alphabet:
    - "0"
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "a"
    - "b"
    - "c"
    - "d"
    - "e"
    - "f"
    - "g"
    - "h"
    - "i"
    - "j"
    - "k"
    - "l"
    - "m"
    - "n"
    - "o"
    - "p"
    - "q"
    - "r"
    - "s"
    - "t"
    - "u"
    - "v"
    - "w"
    - "x"
    - "y"
    - "z"