SELECT d."DEPARTMENT_ID", COALESCE(SUM(e."SALARY"), 0) AS total_salary,
       ROUND(COALESCE(SUM(e."SALARY"), 0) * 100.0 / (SELECT SUM("SALARY") FROM public."EMPLOYEES"), 2) AS percentage
FROM public."DEPARTMENTS" d
LEFT JOIN public."EMPLOYEES" e ON d."DEPARTMENT_ID" = e."DEPARTMENT_ID"
GROUP BY d."DEPARTMENT_ID"
UNION ALL
SELECT NULL, COALESCE(SUM("SALARY"), 0), 
       ROUND(COALESCE(SUM("SALARY"), 0) * 100.0 / (SELECT SUM("SALARY") FROM public."EMPLOYEES"), 2)
FROM public."EMPLOYEES"
WHERE "DEPARTMENT_ID" IS NULL
ORDER BY percentage DESC;

